version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "npm"
    directory: "/apps/CardHero.Frontend.React"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
