component_depth: 2
languages:
- name: csharp
  production:
    exclude:
      - /src/CardHero\.Data\.PostgreSql/EntityFramework/.*\.cs
      - /src/CardHero\.Data\.SqlServer/EntityFramework/.*\.cs
- name: typescript
  production:
    exclude:
      - /apps/CardHero\.Frontend\.React/src/clients/clients\.ts
