version: 1

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/apps/CardHero.Frontend.React"
    update_schedule: "live"

  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
