--
-- PostgreSQL database dump
--

-- Dumped from database version 12.1
-- Dumped by pg_dump version 12.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Card; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."Card" (
    "Card_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "UpAttack" integer NOT NULL,
    "RightAttack" integer NOT NULL,
    "DownAttack" integer NOT NULL,
    "LeftAttack" integer NOT NULL,
    "Health" integer DEFAULT 1 NOT NULL,
    "Attack" integer NOT NULL,
    "Defence" integer NOT NULL,
    "Rarity_FK" integer DEFAULT 1 NOT NULL,
    "TotalStats" integer GENERATED ALWAYS AS ((((((("UpAttack" + "RightAttack") + "DownAttack") + "LeftAttack") + "Health") + "Attack") + "Defence")) STORED NOT NULL
);


ALTER TABLE public."Card" OWNER TO cardhero_user;

--
-- Name: CardCollection; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."CardCollection" (
    "CardCollection_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Card_FK" integer NOT NULL,
    "User_FK" integer NOT NULL,
    "CreatedTime" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."CardCollection" OWNER TO cardhero_user;

--
-- Name: CardCollection_CardCollection_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."CardCollection" ALTER COLUMN "CardCollection_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CardCollection_CardCollection_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CardFavourite; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."CardFavourite" (
    "CardFavourite_PK" integer NOT NULL,
    "Card_FK" integer NOT NULL,
    "User_FK" integer NOT NULL
);


ALTER TABLE public."CardFavourite" OWNER TO cardhero_user;

--
-- Name: CardFavourite_CardFavourite_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."CardFavourite" ALTER COLUMN "CardFavourite_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CardFavourite_CardFavourite_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Card_Card_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."Card" ALTER COLUMN "Card_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Card_Card_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Deck; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."Deck" (
    "Deck_PK" integer NOT NULL,
    "Rowstamp" bytea,
    "CreatedTime" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedTime" timestamp with time zone,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "MaxCards" integer NOT NULL,
    "User_FK" integer NOT NULL
);


ALTER TABLE public."Deck" OWNER TO cardhero_user;

--
-- Name: DeckCardCollection; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."DeckCardCollection" (
    "DeckCardCollection_PK" integer NOT NULL,
    "Rowstamp" bytea,
    "Deck_FK" integer NOT NULL,
    "CardCollection_FK" integer NOT NULL
);


ALTER TABLE public."DeckCardCollection" OWNER TO cardhero_user;

--
-- Name: DeckCardCollection_DeckCardCollection_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."DeckCardCollection" ALTER COLUMN "DeckCardCollection_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DeckCardCollection_DeckCardCollection_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DeckFavourite; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."DeckFavourite" (
    "DeckFavourite_PK" integer NOT NULL,
    "Deck_FK" integer NOT NULL,
    "User_FK" integer NOT NULL
);


ALTER TABLE public."DeckFavourite" OWNER TO cardhero_user;

--
-- Name: DeckFavourite_DeckFavourite_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."DeckFavourite" ALTER COLUMN "DeckFavourite_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DeckFavourite_DeckFavourite_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Deck_Deck_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."Deck" ALTER COLUMN "Deck_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Deck_Deck_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Game; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."Game" (
    "Game_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Name" character varying(100),
    "StartTime" timestamp with time zone DEFAULT now() NOT NULL,
    "EndTime" timestamp with time zone,
    "CurrentGameUser_FK" integer,
    "Winner_FK" integer,
    "Rows" integer DEFAULT 3 NOT NULL,
    "Columns" integer DEFAULT 3 NOT NULL,
    "GameType_FK" integer DEFAULT 1 NOT NULL,
    "MaxPlayers" integer DEFAULT 2 NOT NULL
);


ALTER TABLE public."Game" OWNER TO cardhero_user;

--
-- Name: GameDeck; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."GameDeck" (
    "GameDeck_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Name" character varying(100),
    "Description" character varying(1000),
    "CreatedTime" timestamp with time zone DEFAULT now() NOT NULL,
    "GameUser_FK" integer NOT NULL
);


ALTER TABLE public."GameDeck" OWNER TO cardhero_user;

--
-- Name: GameDeckCardCollection; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."GameDeckCardCollection" (
    "GameDeckCardCollection_PK" integer NOT NULL,
    "Rowstamp" bytea,
    "GameDeck_FK" integer NOT NULL,
    "Card_FK" integer NOT NULL
);


ALTER TABLE public."GameDeckCardCollection" OWNER TO cardhero_user;

--
-- Name: GameDeckCardCollection_GameDeckCardCollection_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."GameDeckCardCollection" ALTER COLUMN "GameDeckCardCollection_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GameDeckCardCollection_GameDeckCardCollection_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GameDeck_GameDeck_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."GameDeck" ALTER COLUMN "GameDeck_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GameDeck_GameDeck_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: GameUser; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."GameUser" (
    "GameUser_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Game_FK" integer NOT NULL,
    "User_FK" integer NOT NULL,
    "JoinedTime" timestamp with time zone DEFAULT now() NOT NULL,
    "Order" integer
);


ALTER TABLE public."GameUser" OWNER TO cardhero_user;

--
-- Name: GameUser_GameUser_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."GameUser" ALTER COLUMN "GameUser_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."GameUser_GameUser_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Game_Game_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."Game" ALTER COLUMN "Game_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Game_Game_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Move; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."Move" (
    "Move_PK" integer NOT NULL,
    "Rowstamp" character(10),
    "CreatedTime" timestamp with time zone DEFAULT now() NOT NULL,
    "Turn_FK" integer NOT NULL,
    "GameDeckCardCollection_FK" integer NOT NULL,
    "Row" integer NOT NULL,
    "Column" integer NOT NULL
);


ALTER TABLE public."Move" OWNER TO cardhero_user;

--
-- Name: Move_Move_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."Move" ALTER COLUMN "Move_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Move_Move_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Rarity; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."Rarity" (
    "Rarity_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Frequency" integer NOT NULL
);


ALTER TABLE public."Rarity" OWNER TO cardhero_user;

--
-- Name: Rarity_Rarity_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."Rarity" ALTER COLUMN "Rarity_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Rarity_Rarity_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: StoreItem; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."StoreItem" (
    "StoreItem_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(1000),
    "Cost" integer NOT NULL,
    "ItemCount" integer DEFAULT 1 NOT NULL,
    "Expiry" timestamp without time zone
);


ALTER TABLE public."StoreItem" OWNER TO cardhero_user;

--
-- Name: StoreItem_StoreItem_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."StoreItem" ALTER COLUMN "StoreItem_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."StoreItem_StoreItem_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Turn; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."Turn" (
    "Turn_PK" integer NOT NULL,
    "Rowstamp" bytea NOT NULL,
    "StartTime" timestamp with time zone DEFAULT now() NOT NULL,
    "EndTime" timestamp with time zone,
    "CurrentGameUser_FK" integer NOT NULL,
    "Game_FK" integer NOT NULL
);


ALTER TABLE public."Turn" OWNER TO cardhero_user;

--
-- Name: Turn_Turn_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."Turn" ALTER COLUMN "Turn_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Turn_Turn_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: cardhero_user
--

CREATE TABLE public."User" (
    "User_PK" integer NOT NULL,
    "Identifier" character varying(50) NOT NULL,
    "CreatedDate" timestamp with time zone DEFAULT now() NOT NULL,
    "FullName" character varying(200),
    "IdPSource" character varying(50) NOT NULL,
    "Coins" bigint NOT NULL
);


ALTER TABLE public."User" OWNER TO cardhero_user;

--
-- Name: User_User_PK_seq; Type: SEQUENCE; Schema: public; Owner: cardhero_user
--

ALTER TABLE public."User" ALTER COLUMN "User_PK" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_User_PK_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Card PK_Card; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Card"
    ADD CONSTRAINT "PK_Card" PRIMARY KEY ("Card_PK");


--
-- Name: CardCollection PK_CardCollection; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."CardCollection"
    ADD CONSTRAINT "PK_CardCollection" PRIMARY KEY ("CardCollection_PK");


--
-- Name: CardFavourite PK_CardFavourite; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."CardFavourite"
    ADD CONSTRAINT "PK_CardFavourite" PRIMARY KEY ("CardFavourite_PK");


--
-- Name: Deck PK_Deck; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Deck"
    ADD CONSTRAINT "PK_Deck" PRIMARY KEY ("Deck_PK");


--
-- Name: DeckCardCollection PK_DeckCardCollection; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."DeckCardCollection"
    ADD CONSTRAINT "PK_DeckCardCollection" PRIMARY KEY ("DeckCardCollection_PK");


--
-- Name: DeckFavourite PK_DeckFavourite; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."DeckFavourite"
    ADD CONSTRAINT "PK_DeckFavourite" PRIMARY KEY ("DeckFavourite_PK");


--
-- Name: Game PK_Game; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Game"
    ADD CONSTRAINT "PK_Game" PRIMARY KEY ("Game_PK");


--
-- Name: GameDeck PK_GameDeck; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameDeck"
    ADD CONSTRAINT "PK_GameDeck" PRIMARY KEY ("GameDeck_PK");


--
-- Name: GameDeckCardCollection PK_GameDeckCardCollection; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameDeckCardCollection"
    ADD CONSTRAINT "PK_GameDeckCardCollection" PRIMARY KEY ("GameDeckCardCollection_PK");


--
-- Name: GameUser PK_GameUser; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameUser"
    ADD CONSTRAINT "PK_GameUser" PRIMARY KEY ("GameUser_PK");


--
-- Name: Move PK_Move; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Move"
    ADD CONSTRAINT "PK_Move" PRIMARY KEY ("Move_PK");


--
-- Name: Rarity PK_Rarity; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Rarity"
    ADD CONSTRAINT "PK_Rarity" PRIMARY KEY ("Rarity_PK");


--
-- Name: StoreItem PK_StoreItem; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."StoreItem"
    ADD CONSTRAINT "PK_StoreItem" PRIMARY KEY ("StoreItem_PK");


--
-- Name: Turn PK_Turn; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Turn"
    ADD CONSTRAINT "PK_Turn" PRIMARY KEY ("Turn_PK");


--
-- Name: User PK_User; Type: CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_User" PRIMARY KEY ("User_PK");


--
-- Name: IX_CardCollection_Card_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_CardCollection_Card_FK" ON public."CardCollection" USING btree ("Card_FK");


--
-- Name: IX_CardCollection_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_CardCollection_User_FK" ON public."CardCollection" USING btree ("User_FK");


--
-- Name: IX_CardFavourite_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_CardFavourite_User_FK" ON public."CardFavourite" USING btree ("User_FK");


--
-- Name: IX_Card_Rarity_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Card_Rarity_FK" ON public."Card" USING btree ("Rarity_FK");


--
-- Name: IX_DeckCardCollection_CardCollection_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_DeckCardCollection_CardCollection_FK" ON public."DeckCardCollection" USING btree ("CardCollection_FK");


--
-- Name: IX_DeckCardCollection_Deck_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_DeckCardCollection_Deck_FK" ON public."DeckCardCollection" USING btree ("Deck_FK");


--
-- Name: IX_DeckFavourite_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_DeckFavourite_User_FK" ON public."DeckFavourite" USING btree ("User_FK");


--
-- Name: IX_Deck_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Deck_User_FK" ON public."Deck" USING btree ("User_FK");


--
-- Name: IX_GameDeckCardCollection_Card_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_GameDeckCardCollection_Card_FK" ON public."GameDeckCardCollection" USING btree ("Card_FK");


--
-- Name: IX_GameDeckCardCollection_GameDeck_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_GameDeckCardCollection_GameDeck_FK" ON public."GameDeckCardCollection" USING btree ("GameDeck_FK");


--
-- Name: IX_GameDeck_GameUser_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_GameDeck_GameUser_FK" ON public."GameDeck" USING btree ("GameUser_FK");


--
-- Name: IX_GameUser_Game_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_GameUser_Game_FK" ON public."GameUser" USING btree ("Game_FK");


--
-- Name: IX_GameUser_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_GameUser_User_FK" ON public."GameUser" USING btree ("User_FK");


--
-- Name: IX_Game_CurrentGameUser_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Game_CurrentGameUser_FK" ON public."Game" USING btree ("CurrentGameUser_FK");


--
-- Name: IX_Game_GameType_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Game_GameType_FK" ON public."Game" USING btree ("GameType_FK");


--
-- Name: IX_Game_Winner_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Game_Winner_FK" ON public."Game" USING btree ("Winner_FK");


--
-- Name: IX_Move_GameDeckCardCollection_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Move_GameDeckCardCollection_FK" ON public."Move" USING btree ("GameDeckCardCollection_FK");


--
-- Name: IX_Move_Turn_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Move_Turn_FK" ON public."Move" USING btree ("Turn_FK");


--
-- Name: IX_Turn_CurrentGameUser_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Turn_CurrentGameUser_FK" ON public."Turn" USING btree ("CurrentGameUser_FK");


--
-- Name: IX_Turn_Game_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE INDEX "IX_Turn_Game_FK" ON public."Turn" USING btree ("Game_FK");


--
-- Name: UX_CardFavourite_Card_FK_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE UNIQUE INDEX "UX_CardFavourite_Card_FK_User_FK" ON public."CardFavourite" USING btree ("Card_FK", "User_FK");


--
-- Name: UX_DeckFavourite_Deck_FK_User_FK; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE UNIQUE INDEX "UX_DeckFavourite_Deck_FK_User_FK" ON public."DeckFavourite" USING btree ("Deck_FK", "User_FK");


--
-- Name: UX_User_Identifier; Type: INDEX; Schema: public; Owner: cardhero_user
--

CREATE UNIQUE INDEX "UX_User_Identifier" ON public."User" USING btree ("Identifier", "IdPSource");


--
-- Name: CardCollection FK_CardCollection_Card_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."CardCollection"
    ADD CONSTRAINT "FK_CardCollection_Card_FK" FOREIGN KEY ("Card_FK") REFERENCES public."Card"("Card_PK") ON DELETE RESTRICT;


--
-- Name: CardCollection FK_CardCollection_User_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."CardCollection"
    ADD CONSTRAINT "FK_CardCollection_User_FK" FOREIGN KEY ("User_FK") REFERENCES public."User"("User_PK") ON DELETE RESTRICT;


--
-- Name: CardFavourite FK_CardFavourite_Card_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."CardFavourite"
    ADD CONSTRAINT "FK_CardFavourite_Card_FK" FOREIGN KEY ("Card_FK") REFERENCES public."Card"("Card_PK") ON DELETE RESTRICT;


--
-- Name: CardFavourite FK_CardFavourite_User_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."CardFavourite"
    ADD CONSTRAINT "FK_CardFavourite_User_FK" FOREIGN KEY ("User_FK") REFERENCES public."User"("User_PK") ON DELETE RESTRICT;


--
-- Name: Card FK_Card_Rarity_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Card"
    ADD CONSTRAINT "FK_Card_Rarity_FK" FOREIGN KEY ("Rarity_FK") REFERENCES public."Rarity"("Rarity_PK") ON DELETE RESTRICT;


--
-- Name: DeckCardCollection FK_DeckCardCollection_CardCollection_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."DeckCardCollection"
    ADD CONSTRAINT "FK_DeckCardCollection_CardCollection_FK" FOREIGN KEY ("CardCollection_FK") REFERENCES public."CardCollection"("CardCollection_PK") ON DELETE RESTRICT;


--
-- Name: DeckCardCollection FK_DeckCardCollection_Deck_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."DeckCardCollection"
    ADD CONSTRAINT "FK_DeckCardCollection_Deck_FK" FOREIGN KEY ("Deck_FK") REFERENCES public."Deck"("Deck_PK") ON DELETE RESTRICT;


--
-- Name: DeckFavourite FK_DeckFavourite_Deck_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."DeckFavourite"
    ADD CONSTRAINT "FK_DeckFavourite_Deck_FK" FOREIGN KEY ("Deck_FK") REFERENCES public."Deck"("Deck_PK") ON DELETE RESTRICT;


--
-- Name: DeckFavourite FK_DeckFavourite_User_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."DeckFavourite"
    ADD CONSTRAINT "FK_DeckFavourite_User_FK" FOREIGN KEY ("User_FK") REFERENCES public."User"("User_PK") ON DELETE RESTRICT;


--
-- Name: Deck FK_Deck_User_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Deck"
    ADD CONSTRAINT "FK_Deck_User_FK" FOREIGN KEY ("User_FK") REFERENCES public."User"("User_PK") ON DELETE RESTRICT;


--
-- Name: GameDeckCardCollection FK_GameDeckCardCollection_Card_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameDeckCardCollection"
    ADD CONSTRAINT "FK_GameDeckCardCollection_Card_FK" FOREIGN KEY ("Card_FK") REFERENCES public."Card"("Card_PK") ON DELETE RESTRICT;


--
-- Name: GameDeckCardCollection FK_GameDeckCardCollection_GameDeck_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameDeckCardCollection"
    ADD CONSTRAINT "FK_GameDeckCardCollection_GameDeck_FK" FOREIGN KEY ("GameDeck_FK") REFERENCES public."GameDeck"("GameDeck_PK") ON DELETE RESTRICT;


--
-- Name: GameDeck FK_GameDeck_GameUser_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameDeck"
    ADD CONSTRAINT "FK_GameDeck_GameUser_FK" FOREIGN KEY ("GameUser_FK") REFERENCES public."GameUser"("GameUser_PK") ON DELETE RESTRICT;


--
-- Name: GameUser FK_GameUser_Game; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameUser"
    ADD CONSTRAINT "FK_GameUser_Game" FOREIGN KEY ("Game_FK") REFERENCES public."Game"("Game_PK") ON DELETE RESTRICT;


--
-- Name: GameUser FK_GameUser_User; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."GameUser"
    ADD CONSTRAINT "FK_GameUser_User" FOREIGN KEY ("User_FK") REFERENCES public."User"("User_PK") ON DELETE RESTRICT;


--
-- Name: Game FK_Game_CurrentUser_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Game"
    ADD CONSTRAINT "FK_Game_CurrentUser_FK" FOREIGN KEY ("CurrentGameUser_FK") REFERENCES public."GameUser"("GameUser_PK") ON DELETE RESTRICT;


--
-- Name: Game FK_Game_Winner_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Game"
    ADD CONSTRAINT "FK_Game_Winner_FK" FOREIGN KEY ("Winner_FK") REFERENCES public."GameUser"("GameUser_PK") ON DELETE RESTRICT;


--
-- Name: Move FK_Move_CardCollection_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Move"
    ADD CONSTRAINT "FK_Move_CardCollection_FK" FOREIGN KEY ("GameDeckCardCollection_FK") REFERENCES public."GameDeckCardCollection"("GameDeckCardCollection_PK") ON DELETE RESTRICT;


--
-- Name: Move FK_Move_Turn_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Move"
    ADD CONSTRAINT "FK_Move_Turn_FK" FOREIGN KEY ("Turn_FK") REFERENCES public."Turn"("Turn_PK") ON DELETE RESTRICT;


--
-- Name: Turn FK_Turn_CurrentUser_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Turn"
    ADD CONSTRAINT "FK_Turn_CurrentUser_FK" FOREIGN KEY ("CurrentGameUser_FK") REFERENCES public."GameUser"("GameUser_PK") ON DELETE RESTRICT;


--
-- Name: Turn FK_Turn_Game_FK; Type: FK CONSTRAINT; Schema: public; Owner: cardhero_user
--

ALTER TABLE ONLY public."Turn"
    ADD CONSTRAINT "FK_Turn_Game_FK" FOREIGN KEY ("Game_FK") REFERENCES public."Game"("Game_PK") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

